<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('categories')->delete();
        
        \DB::table('categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Entreprises & Commerce',
                'slug' => 'entreprises-commerce',
                'description' => 'Procédures liées au commerce, artisanat et création d\'entreprise',
                'icon' => 'fas fa-store',
                'color' => 'green',
                'order' => 1,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Communication & Numérique',
                'slug' => 'communication-numerique',
                'description' => 'Communication, audiovisuel et technologies de l\'information',
                'icon' => 'fas fa-satellite-dish',
                'color' => 'blue',
                'order' => 2,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Fiscalité & Finances',
                'slug' => 'fiscalite-finances',
                'description' => 'Impôts, taxes, finances publiques et commandes publiques',
                'icon' => 'fas fa-coins',
                'color' => 'slate',
                'order' => 3,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Famille & Action sociale',
                'slug' => 'famille-action-sociale',
                'description' => 'Démarches liées à la famille, au genre et aux services sociaux',
                'icon' => 'fas fa-users',
                'color' => 'purple',
                'order' => 4,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Travail & Emploi',
                'slug' => 'travail-emploi',
                'description' => 'Emploi, formation professionnelle et protection sociale',
                'icon' => 'fas fa-briefcase',
                'color' => 'orange',
                'order' => 5,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Justice & Droits',
                'slug' => 'justice-droits',
                'description' => 'Justice, droits humains et civisme',
                'icon' => 'fas fa-gavel',
                'color' => 'teal',
                'order' => 6,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Éducation & Recherche',
                'slug' => 'education-recherche',
                'description' => 'Enseignement, bourses, formation et recherche scientifique',
                'icon' => 'fas fa-graduation-cap',
                'color' => 'blue',
                'order' => 7,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Santé & Protection sociale',
                'slug' => 'sante-protection-sociale',
                'description' => 'Santé humaine et protection sociale',
                'icon' => 'fas fa-heartbeat',
                'color' => 'red',
                'order' => 8,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Transport & Mobilité',
                'slug' => 'transport-mobilite',
                'description' => 'Transport, logistique et mobilité',
                'icon' => 'fas fa-car',
                'color' => 'orange',
                'order' => 9,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Agriculture & Élevage',
                'slug' => 'agriculture-elevage',
                'description' => 'Agriculture, élevage et pêche',
                'icon' => 'fas fa-seedling',
                'color' => 'green',
                'order' => 10,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Environnement & Ressources',
                'slug' => 'environnement-ressources',
                'description' => 'Environnement, ressources naturelles, mines et énergie',
                'icon' => 'fas fa-leaf',
                'color' => 'green',
                'order' => 11,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Travaux publics & Urbanisme',
                'slug' => 'travaux-publics-urbanisme',
                'description' => 'Construction, urbanisme, habitat et aménagement du territoire',
                'icon' => 'fas fa-hard-hat',
                'color' => 'orange',
                'order' => 12,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Gouvernance & Institutions',
                'slug' => 'gouvernance-institutions',
                'description' => 'Gouvernance administrative, politique et institutions publiques',
                'icon' => 'fas fa-landmark',
                'color' => 'slate',
                'order' => 13,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Papiers & Citoyenneté',
                'slug' => 'papiers-citoyennete',
                'description' => 'État civil, décentralisation, sécurité et protection civile',
                'icon' => 'fas fa-id-card',
                'color' => 'blue',
                'order' => 14,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Sport & Loisirs',
                'slug' => 'sport-loisirs',
                'description' => 'Sport, loisirs et promotion de la jeunesse',
                'icon' => 'fas fa-running',
                'color' => 'orange',
                'order' => 15,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Culture & Tourisme',
                'slug' => 'culture-tourisme',
                'description' => 'Arts, culture et tourisme',
                'icon' => 'fas fa-palette',
                'color' => 'purple',
                'order' => 16,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Diaspora & Coopération',
                'slug' => 'diaspora-cooperation',
                'description' => 'Immigration, émigration et diplomatie',
                'icon' => 'fas fa-globe-africa',
                'color' => 'blue',
                'order' => 17,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Médiation',
                'slug' => 'mediation',
                'description' => 'Médiation dans le secteur public',
                'icon' => 'fas fa-handshake',
                'color' => 'teal',
                'order' => 18,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Fonction publique',
                'slug' => 'fonction-publique',
                'description' => 'Gestion de carrière et recrutement dans la fonction publique',
                'icon' => 'fas fa-user-tie',
                'color' => 'slate',
                'order' => 19,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Autres démarches',
                'slug' => 'autres-demarches',
                'description' => 'Autres démarches administratives',
                'icon' => 'fas fa-folder',
                'color' => 'slate',
                'order' => 20,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Communication audio-visuelle',
                'slug' => 'communication-audio-visuelle',
                'description' => 'Procédures liées à : Communication audio-visuelle',
                'icon' => 'fas fa-tv',
                'color' => '#009E49',
                'order' => 1,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Médiation dans le public',
                'slug' => 'mediation-dans-le-public',
                'description' => 'Procédures liées à : Médiation dans le public',
                'icon' => 'fas fa-handshake',
                'color' => '#2563EB',
                'order' => 2,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Autres',
                'slug' => 'autres',
                'description' => 'Procédures liées à : Autres',
                'icon' => 'fas fa-folder-open',
                'color' => '#DC2626',
                'order' => 3,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Construction d\'ouvrages',
                'slug' => 'construction-d-ouvrages',
                'description' => 'Procédures liées à : Construction d\'ouvrages',
                'icon' => 'fas fa-hard-hat',
                'color' => '#D97706',
                'order' => 4,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Transport',
                'slug' => 'transport',
                'description' => 'Procédures liées à : Transport',
                'icon' => 'fas fa-bus',
                'color' => '#7C3AED',
                'order' => 5,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Activités commerciales',
                'slug' => 'activites-commerciales',
                'description' => 'Procédures liées à : Activités commerciales',
                'icon' => 'fas fa-store',
                'color' => '#0891B2',
                'order' => 6,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Promotion de la justice',
                'slug' => 'promotion-de-la-justice',
                'description' => 'Procédures liées à : Promotion de la justice',
                'icon' => 'fas fa-balance-scale-right',
                'color' => '#BE185D',
                'order' => 7,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Gestion de carrière',
                'slug' => 'gestion-de-carriere',
                'description' => 'Procédures liées à : Gestion de carrière',
                'icon' => 'fas fa-chart-line',
                'color' => '#059669',
                'order' => 8,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Services sociaux',
                'slug' => 'services-sociaux',
                'description' => 'Procédures liées à : Services sociaux',
                'icon' => 'fas fa-people-carry',
                'color' => '#4F46E5',
                'order' => 9,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Formation professionnelle',
                'slug' => 'formation-professionnelle',
                'description' => 'Procédures liées à : Formation professionnelle',
                'icon' => 'fas fa-tools',
                'color' => '#CA8A04',
                'order' => 10,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Administration du travail',
                'slug' => 'administration-du-travail',
                'description' => 'Procédures liées à : Administration du travail',
                'icon' => 'fas fa-briefcase',
                'color' => '#009E49',
                'order' => 11,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Emploi',
                'slug' => 'emploi',
                'description' => 'Procédures liées à : Emploi',
                'icon' => 'fas fa-user-tie',
                'color' => '#2563EB',
                'order' => 12,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Arts et culture',
                'slug' => 'arts-et-culture',
                'description' => 'Procédures liées à : Arts et culture',
                'icon' => 'fas fa-palette',
                'color' => '#DC2626',
                'order' => 13,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Femme et Genre',
                'slug' => 'femme-et-genre',
                'description' => 'Procédures liées à : Femme et Genre',
                'icon' => 'fas fa-female',
                'color' => '#D97706',
                'order' => 14,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Comptabilité publique',
                'slug' => 'comptabilite-publique',
                'description' => 'Procédures liées à : Comptabilité publique',
                'icon' => 'fas fa-calculator',
                'color' => '#7C3AED',
                'order' => 15,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Eau',
                'slug' => 'eau',
                'description' => 'Procédures liées à : Eau',
                'icon' => 'fas fa-tint',
                'color' => '#0891B2',
                'order' => 16,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Secteur agricole',
                'slug' => 'secteur-agricole',
                'description' => 'Procédures liées à : Secteur agricole',
                'icon' => 'fas fa-seedling',
                'color' => '#BE185D',
                'order' => 17,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Impôts et taxes',
                'slug' => 'impots-et-taxes',
                'description' => 'Procédures liées à : Impôts et taxes',
                'icon' => 'fas fa-file-invoice-dollar',
                'color' => '#059669',
                'order' => 18,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Dépenses publiques',
                'slug' => 'depenses-publiques',
                'description' => 'Procédures liées à : Dépenses publiques',
                'icon' => 'fas fa-money-bill-wave',
                'color' => '#4F46E5',
                'order' => 19,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Commandes publiques',
                'slug' => 'commandes-publiques',
                'description' => 'Procédures liées à : Commandes publiques',
                'icon' => 'fas fa-file-contract',
                'color' => '#CA8A04',
                'order' => 20,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Décentralisation',
                'slug' => 'decentralisation',
                'description' => 'Procédures liées à : Décentralisation',
                'icon' => 'fas fa-map-marked-alt',
                'color' => '#009E49',
                'order' => 21,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Information géographique',
                'slug' => 'information-geographique',
                'description' => 'Procédures liées à : Information géographique',
                'icon' => 'fas fa-map',
                'color' => '#2563EB',
                'order' => 22,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Secteur de l\'élevage',
                'slug' => 'secteur-de-l-elevage',
                'description' => 'Procédures liées à : Secteur de l\'élevage',
                'icon' => 'fas fa-horse',
                'color' => '#DC2626',
                'order' => 23,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Faune',
                'slug' => 'faune',
                'description' => 'Procédures liées à : Faune',
                'icon' => 'fas fa-paw',
                'color' => '#D97706',
                'order' => 24,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Tourisme',
                'slug' => 'tourisme',
                'description' => 'Procédures liées à : Tourisme',
                'icon' => 'fas fa-plane',
                'color' => '#7C3AED',
                'order' => 25,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Promotion des énergies renouvelables',
                'slug' => 'promotion-des-energies-renouvelables',
                'description' => 'Procédures liées à : Promotion des énergies renouvelables',
                'icon' => 'fas fa-solar-panel',
                'color' => '#0891B2',
                'order' => 26,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Bâtiments',
                'slug' => 'batiments',
                'description' => 'Procédures liées à : Bâtiments',
                'icon' => 'fas fa-building',
                'color' => '#BE185D',
                'order' => 27,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Contentieux Électoraux',
                'slug' => 'contentieux-electoraux',
                'description' => 'Procédures liées à : Contentieux Électoraux',
                'icon' => 'fas fa-gavel',
                'color' => '#059669',
                'order' => 28,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Création d\'entreprise',
                'slug' => 'creation-d-entreprise',
                'description' => 'Procédures liées à : Création d\'entreprise',
                'icon' => 'fas fa-rocket',
                'color' => '#4F46E5',
                'order' => 29,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Diplomatie',
                'slug' => 'diplomatie',
                'description' => 'Procédures liées à : Diplomatie',
                'icon' => 'fas fa-globe-africa',
                'color' => '#CA8A04',
                'order' => 30,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Distinction honorifique',
                'slug' => 'distinction-honorifique',
                'description' => 'Procédures liées à : Distinction honorifique',
                'icon' => 'fas fa-medal',
                'color' => '#009E49',
                'order' => 31,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Enseignement',
                'slug' => 'enseignement',
                'description' => 'Procédures liées à : Enseignement',
                'icon' => 'fas fa-chalkboard-teacher',
                'color' => '#2563EB',
                'order' => 32,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Gouvernance administrative',
                'slug' => 'gouvernance-administrative',
                'description' => 'Procédures liées à : Gouvernance administrative',
                'icon' => 'fas fa-university',
                'color' => '#DC2626',
                'order' => 33,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Pêche',
                'slug' => 'peche',
                'description' => 'Procédures liées à : Pêche',
                'icon' => 'fas fa-fish',
                'color' => '#D97706',
                'order' => 34,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Recrutement',
                'slug' => 'recrutement',
                'description' => 'Procédures liées à : Recrutement',
                'icon' => 'fas fa-user-plus',
                'color' => '#7C3AED',
                'order' => 35,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Communication',
                'slug' => 'communication',
                'description' => 'Procédures liées à : Communication',
                'icon' => 'fas fa-bullhorn',
                'color' => '#0891B2',
                'order' => 36,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Formation',
                'slug' => 'formation',
                'description' => 'Procédures liées à : Formation',
                'icon' => 'fas fa-book-reader',
                'color' => '#BE185D',
                'order' => 37,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Mines',
                'slug' => 'mines',
                'description' => 'Procédures liées à : Mines',
                'icon' => 'fas fa-mountain',
                'color' => '#059669',
                'order' => 38,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Promotion du sport',
                'slug' => 'promotion-du-sport',
                'description' => 'Procédures liées à : Promotion du sport',
                'icon' => 'fas fa-running',
                'color' => '#4F46E5',
                'order' => 39,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Protection de l\'environnement',
                'slug' => 'protection-de-l-environnement',
                'description' => 'Procédures liées à : Protection de l\'environnement',
                'icon' => 'fas fa-leaf',
                'color' => '#CA8A04',
                'order' => 40,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Protection sociale',
                'slug' => 'protection-sociale',
                'description' => 'Procédures liées à : Protection sociale',
                'icon' => 'fas fa-hands-helping',
                'color' => '#009E49',
                'order' => 41,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Assainissement',
                'slug' => 'assainissement',
                'description' => 'Procédures liées à : Assainissement',
                'icon' => 'fas fa-recycle',
                'color' => '#2563EB',
                'order' => 42,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Logistique',
                'slug' => 'logistique',
                'description' => 'Procédures liées à : Logistique',
                'icon' => 'fas fa-truck',
                'color' => '#DC2626',
                'order' => 43,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Promotion de la jeunesse',
                'slug' => 'promotion-de-la-jeunesse',
                'description' => 'Procédures liées à : Promotion de la jeunesse',
                'icon' => 'fas fa-child',
                'color' => '#D97706',
                'order' => 44,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Promotion des droits humains',
                'slug' => 'promotion-des-droits-humains',
                'description' => 'Procédures liées à : Promotion des droits humains',
                'icon' => 'fas fa-hand-holding-heart',
                'color' => '#7C3AED',
                'order' => 45,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Protection civile',
                'slug' => 'protection-civile',
                'description' => 'Procédures liées à : Protection civile',
                'icon' => 'fas fa-shield-alt',
                'color' => '#0891B2',
                'order' => 46,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'Recherche scientifique',
                'slug' => 'recherche-scientifique',
                'description' => 'Procédures liées à : Recherche scientifique',
                'icon' => 'fas fa-flask',
                'color' => '#BE185D',
                'order' => 47,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Régulation Institutions/Politiques',
                'slug' => 'regulation-institutionspolitiques',
                'description' => 'Procédures liées à : Régulation Institutions/Politiques',
                'icon' => 'fas fa-landmark',
                'color' => '#059669',
                'order' => 48,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'Santé humaine',
                'slug' => 'sante-humaine',
                'description' => 'Procédures liées à : Santé humaine',
                'icon' => 'fas fa-heartbeat',
                'color' => '#4F46E5',
                'order' => 49,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Bourses d\'études/Prêts et Aides',
                'slug' => 'bourses-d-etudesprets-et-aides',
                'description' => 'Procédures liées à : Bourses d\'études/Prêts et Aides',
                'icon' => 'fas fa-graduation-cap',
                'color' => '#CA8A04',
                'order' => 50,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Contrôle de constitutionnalité',
                'slug' => 'controle-de-constitutionnalite',
                'description' => 'Procédures liées à : Contrôle de constitutionnalité',
                'icon' => 'fas fa-landmark',
                'color' => '#009E49',
                'order' => 51,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'Contrôle des Partis Politiques',
                'slug' => 'controle-des-partis-politiques',
                'description' => 'Procédures liées à : Contrôle des Partis Politiques',
                'icon' => 'fas fa-users',
                'color' => '#2563EB',
                'order' => 52,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'Loisirs',
                'slug' => 'loisirs',
                'description' => 'Procédures liées à : Loisirs',
                'icon' => 'fas fa-futbol',
                'color' => '#DC2626',
                'order' => 53,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'Aménagements urbains',
                'slug' => 'amenagements-urbains',
                'description' => 'Procédures liées à : Aménagements urbains',
                'icon' => 'fas fa-city',
                'color' => '#D97706',
                'order' => 54,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'Concurrence',
                'slug' => 'concurrence',
                'description' => 'Procédures liées à : Concurrence',
                'icon' => 'fas fa-balance-scale',
                'color' => '#7C3AED',
                'order' => 55,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'Etat civil',
                'slug' => 'etat-civil',
                'description' => 'Procédures liées à : Etat civil',
                'icon' => 'fas fa-id-card',
                'color' => '#0891B2',
                'order' => 56,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'Gouvernance économique',
                'slug' => 'gouvernance-economique',
                'description' => 'Procédures liées à : Gouvernance économique',
                'icon' => 'fas fa-coins',
                'color' => '#BE185D',
                'order' => 57,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'Gouvernance politique',
                'slug' => 'gouvernance-politique',
                'description' => 'Procédures liées à : Gouvernance politique',
                'icon' => 'fas fa-flag',
                'color' => '#059669',
                'order' => 58,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'Prêts, aides et dons',
                'slug' => 'prets-aides-et-dons',
                'description' => 'Procédures liées à : Prêts, aides et dons',
                'icon' => 'fas fa-hand-holding-usd',
                'color' => '#4F46E5',
                'order' => 59,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'Révision constitutionnelle',
                'slug' => 'revision-constitutionnelle',
                'description' => 'Procédures liées à : Révision constitutionnelle',
                'icon' => 'fas fa-scroll',
                'color' => '#CA8A04',
                'order' => 60,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'Sécurité',
                'slug' => 'securite',
                'description' => 'Procédures liées à : Sécurité',
                'icon' => 'fas fa-lock',
                'color' => '#009E49',
                'order' => 61,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'TIC',
                'slug' => 'tic',
                'description' => 'Procédures liées à : TIC',
                'icon' => 'fas fa-laptop-code',
                'color' => '#2563EB',
                'order' => 62,
                'is_active' => 1,
                'meta_title' => NULL,
                'meta_description' => NULL,
                'created_at' => '2026-02-23 21:24:06',
                'updated_at' => '2026-02-23 21:24:06',
            ),
        ));
        
        
    }
}