<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EservicesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('eservices')->delete();
        
        \DB::table('eservices')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 20,
                'title' => '1 etudiant1 ordinateur',
                'slug' => '1-etudiant1-ordinateur',
                'description' => '"Permettre à chaque étudiant burkinabè inscrit dans un établissement d’enseignement supérieur public de disposer d’un ordinateur portable personnel, à coût subventionné"',
                'url' => 'https://ordinateur.campusfaso.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 1,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 2,
                'title' => 'Agrément de bureau prive de placement etou dentreprise de travail temporaire',
                'slug' => 'agrement-de-bureau-prive-de-placement-etou-dentreprise-de-travail-temporaire',
                'description' => 'Demandes d\'agrément de Bureau Privé de Placement et/ou d\'Entreprise de Travail Temporaire du Ministère de la Fonction Publique du Travail et de la Sécurité Sociale du Burkina Faso',
                'url' => 'http://aobop.fonction-publique.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 2,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 16,
                'title' => 'Agrément de construction des etablissements touristiques dhebergement eth',
                'slug' => 'agrement-de-construction-des-etablissements-touristiques-dhebergement-eth',
            'description' => 'L’agrément de réalisation (construction, extension ou transformation) des ETH est un document administratif qui permet à un promoteur de construire ou d’aménager un établissement à caractère commercial ou non qui offre en location des chambres, suites de chambres ou unités de logement équipées et meublées, à une clientèle principalement touristique.',
                'url' => 'https://eservices-mccat.gov.bf/agrealeth-choisir',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 3,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 17,
                'title' => 'Agrément de realisation d\'un etablissements touristiques de loisirs etl',
                'slug' => 'agrement-de-realisation-dun-etablissements-touristiques-de-loisirs-etl',
                'description' => 'L’agrément de réalisation des ETL est un document administratif qui permet à un promoteur de construire ou aménager des infrastructures de loisirs',
                'url' => 'https://eservices-mccat.gov.bf/login',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 4,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 7,
                'title' => 'Agrément technique dans le domaine de leau',
                'slug' => 'agrement-technique-dans-le-domaine-de-leau',
                'description' => 'La plateforme de gestion des agréments Techniques permet de vérifier l’authenticité, la conformité et la validité des agréments techniques dans le domaine de l’eau et assainissement',
                'url' => 'https://agrement.eaubf.net/public/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 5,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 1,
                'title' => 'Agrément technique eau et assainissement',
                'slug' => 'agrement-technique-eau-et-assainissement',
                'description' => '"E-service permettant de demander l\'Agrément technique eau et assainissement. L’exercice des entreprises et bureaux d’études dans le domaine de l’eau et de l’assainissement est soumis à la possession d’un agrément technique échelonné en catégories pour les différents types de prestations.
L’octroi de cet agrément technique est conditionné par l’achat d’un dossier puis le montage de ce dossier par l’entreprise qui sera déposé à la DGRE. Les dossiers reçus sont traités par la Commission d’Attribution des Agréments Techniques (CAAT) au cours d’une session semestrielle pour donner suite aux demandes. A la fin de chaque session de la CAAT, un PV est produit et délivré aux bénéficiaires et un projet d’arrêté est élaboré et soumis au contrôle de la DGCMEF avant d’être signé par le Ministre en charge de l’Eau et de l’Assainissement."',
                    'url' => 'https://eservices.envieau.gov.bf/login/P002',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 6,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-23 21:26:45',
                ),
                6 => 
                array (
                    'id' => 7,
                    'category_id' => 11,
                    'title' => 'Agrément technique en matiere dinformatique',
                    'slug' => 'agrement-technique-en-matiere-dinformatique',
                    'description' => 'Demande d\'Agrément Technique en matière d\'Informatique',
                    'url' => 'http://ati.gov.bf/',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 7,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-23 21:26:45',
                ),
                7 => 
                array (
                    'id' => 8,
                    'category_id' => 4,
                    'title' => 'Alias',
                    'slug' => 'alias',
                'description' => 'Système d’accès en ligne aux informations administrative et salariales (ALIAS)',
                    'url' => 'http://www.alias.gov.bf/',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 8,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-23 21:26:45',
                ),
                8 => 
                array (
                    'id' => 9,
                    'category_id' => 3,
                    'title' => 'Ankaaso',
                    'slug' => 'ankaaso',
                    'description' => 'plateforme permettant de soumettre une demande de type de logement , de suivre sa demande',
                    'url' => 'http://www.ankaaso.gov.bf/',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 9,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-21 00:02:42',
                ),
                9 => 
                array (
                    'id' => 10,
                    'category_id' => 19,
                    'title' => 'Attestation d\'artiste',
                    'slug' => 'attestation-dartiste',
                    'description' => 'L’attestation d’artiste est un document administratif qui permet à un artiste d’exercer sa profession',
                    'url' => 'https://eservices-mccat.gov.bf/login',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 10,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-21 00:02:42',
                ),
                10 => 
                array (
                    'id' => 11,
                    'category_id' => 13,
                    'title' => 'Demande d\' Attestation de Travail',
                    'slug' => 'demande-d-attestation-de-travail',
                    'description' => 'Ministère de la Fonction Publique du Travail et de la Sécurité Sociale du Burkina Faso Demande Attestation de Travail',
                    'url' => 'https://www.montravail.gov.bf/',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 11,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-21 00:02:42',
                ),
                11 => 
                array (
                    'id' => 12,
                    'category_id' => 6,
                    'title' => 'Atuc agrément technique de lurbanisme et de la construction',
                    'slug' => 'atuc-agrement-technique-de-lurbanisme-et-de-la-construction',
                    'description' => 'plateforme permettant de soumettre une demande d\'agrément, de suivre sa demande',
                    'url' => 'http://www.atuc.gov.bf/',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 12,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-23 21:26:45',
                ),
                12 => 
                array (
                    'id' => 13,
                    'category_id' => 18,
                    'title' => 'Authentification des diplomes et attestations',
                    'slug' => 'authentification-des-diplomes-et-attestations',
                    'description' => 'Authentification des diplômes et attestations',
                    'url' => 'http://authentificationdiplomes.ujkz.gov.bf/',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 13,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-23 21:26:45',
                ),
                13 => 
                array (
                    'id' => 14,
                    'category_id' => 14,
                    'title' => 'Authentification des immatriculations provisoires et temporaires',
                    'slug' => 'authentification-des-immatriculations-provisoires-et-temporaires',
                    'description' => 'Plateforme d’authentification des immatriculations provisoires et permanentes.',
                    'url' => 'https://www.dgttmverif.bf/',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 14,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-21 00:02:42',
                ),
                14 => 
                array (
                    'id' => 15,
                    'category_id' => 8,
                    'title' => 'Autorisation de gestion des dechets solides',
                    'slug' => 'autorisation-de-gestion-des-dechets-solides',
                    'description' => 'E-service permettant de demander l\'Autorisation de gestion des déchets Solides. La délivrance des autorisations de gestion des déchets solide réponds à une application de l’article 53 du code de l’Environnement et concerne les déchets spéciaux tels que les ferrailles, les huiles usées, les batteries usagés, les métaux non ferreux….',
                    'url' => 'https://eservices.envieau.gov.bf/login/P008',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 15,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-23 21:26:45',
                ),
                15 => 
                array (
                    'id' => 16,
                    'category_id' => 15,
                    'title' => 'Autorisation de participation',
                    'slug' => 'autorisation-de-participation',
                'description' => 'L’autorisation de participation est un document administratif permettant au (x) bénéficiaire (s) de participer sur invitation à un évènement culturel hors du pays',
                    'url' => 'https://eservices-mccat.gov.bf/demandes-art',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 16,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-21 00:02:42',
                ),
                16 => 
                array (
                    'id' => 17,
                    'category_id' => 9,
                    'title' => 'Autorisation denseigner au post primaire et au secondaire',
                    'slug' => 'autorisation-denseigner-au-post-primaire-et-au-secondaire',
                    'description' => 'Demande d\'Autorisation d\'Enseigner au Post-Primaire et au Secondaire du Ministère de l’Education Nationale, de l’Alphabétisation et de la Promotion des Langues Nationales du Burkina Faso',
                    'url' => 'http://autorisationdenseigner.mesrsi.gov.bf/',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 17,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-23 21:26:45',
                ),
                17 => 
                array (
                    'id' => 18,
                    'category_id' => 5,
                    'title' => 'Autorisation d\'exercer le commerce aec',
                    'slug' => 'autorisation-dexercer-le-commerce-aec',
                    'description' => 'Une Autorisation d\'Exercer le Commerce est un acte délivré par le Ministère du Commerce, de l\'Industrie et de l\'Artisanat qui autorise toute personne qui n\'est pas de nationalité burkinabé à exercer le commerce sur le territoire national.',
                    'url' => 'https://peb.bf/actes-administratifs/autorisation-d-exercer-le-commerce',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 18,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-23 21:26:45',
                ),
                18 => 
                array (
                    'id' => 19,
                    'category_id' => 12,
                    'title' => 'Autorisation d\'exercice des activités de la profession cinématograhique et audiovisuelle',
                    'slug' => 'autorisation-dexercice-des-activites-de-la-profession-cinematograhique-et-audiovisuelle',
                    'description' => 'L’autorisation d’exercice de la profession cinématographique et audiovisuelle est un document administratif qui permet au bénéficiaire d’exercer les activités cinématographiques et audiovisuelles',
                    'url' => 'https://eservices-mccat.gov.bf/login',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 19,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-21 00:02:42',
                ),
                19 => 
                array (
                    'id' => 20,
                    'category_id' => 10,
                    'title' => 'Autorisation d\'exploiter un ETL',
                    'slug' => 'autorisation-dexploiter-un-etl',
                'description' => 'L’autorisation d’exploiter d’un établissement touristique de loisirs (ETL) est un document administratif qui permet à un promoteur d’exploiter un établissement touristique de loisirs',
                    'url' => 'https://eservices-mccat.gov.bf/login',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 20,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-21 00:02:42',
                ),
                20 => 
                array (
                    'id' => 21,
                    'category_id' => 20,
                    'title' => 'Autorisation dexploiter un restaurant de tourisme rt',
                    'slug' => 'autorisation-dexploiter-un-restaurant-de-tourisme-rt',
                    'description' => 'Le renouvellement de l’autorisation d’exploiter un restaurant de tourisme ou de l’autorisation d’exploiter une succursale d’un restaurant de tourisme est un document administratif qui permet au promoteur de poursuivre l’exploitation de son entreprise',
                    'url' => 'https://eservices-mccat.gov.bf/autexprt-choisir',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 21,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-23 21:26:45',
                ),
                21 => 
                array (
                    'id' => 22,
                    'category_id' => 2,
                    'title' => 'Autorisation speciale d\'importation asi',
                    'slug' => 'autorisation-speciale-dimportation-asi',
                    'description' => 'Une Autorisation Spéciale d\'Importation est un acte délivré par le Ministère du Commerce, de l\'Industrie et de l\'Artisanat pour un certain nombre de produits encadré par un texte juridique.',
                    'url' => 'https://peb.bf/actes-administratifs/autorisation-speciale-d-importation',
                    'source_file' => NULL,
                    'is_active' => 1,
                    'is_featured' => 0,
                    'order' => 22,
                    'created_at' => '2026-02-20 19:37:36',
                    'updated_at' => '2026-02-23 21:26:45',
                ),
                22 => 
                array (
                    'id' => 23,
                    'category_id' => 16,
                    'title' => 'Avis technique d\'importation de produits chimiques',
                    'slug' => 'avis-technique-dimportation-de-produits-chimiques',
                'description' => '"Permet de demander un avis technique d\'importation de produits chimiques. L’importation des produits chimiques est soumise à une autorisation spéciale délivrée par la Direction des Guichets Uniques du Commerce et de l’Investissement (DGUCI) après avis technique du MEEA précisément la Direction générale de la préservation de l’environnement (DGPE).
 L’avis technique est obtenu après examen d’une demande timbrée à 200 FCFA adressée à Mr le DGPE."',
                'url' => 'https://eservices.envieau.gov.bf/login/P001',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 23,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            23 => 
            array (
                'id' => 24,
                'category_id' => 17,
                'title' => 'Campusfaso',
                'slug' => 'campusfaso',
                'description' => '"CAMPUSFASO est la plateforme qui centralise et dématérialise l’admission, l’orientation et la gestion des dossiers  académiques des étudiants dans toutes les institutions publiques et privées conventionnées."',
                'url' => 'https://www.campusfaso.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 24,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            24 => 
            array (
                'id' => 25,
                'category_id' => 7,
                'title' => 'Cefore création dentreprise',
                'slug' => 'cefore-creation-dentreprise',
                'description' => 'Afin d\'exercer légalement le commerce au Burkina Faso, comme personne physique, vous devez vous enregistrer au registre de commerce, auprès du service des impôts, de la sécurité sociale et au Ministère du Commerce.',
                'url' => 'https://creerentreprise.me.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 25,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            25 => 
            array (
                'id' => 26,
                'category_id' => 1,
                'title' => 'Certificat dexemption des emballages et sachets non biodegradables',
                'slug' => 'certificat-dexemption-des-emballages-et-sachets-non-biodegradables',
                'description' => '"E-service permettant de demander le Certificat d\'exemption des emballages et sachets non biodégradables. Les certificats d’exemptions constituent une dérogation de la loi 017 portant interdiction de la production, de l’importation, de la commercialisation et de la distribution des emballages et sachets plastiques non biodégradable au Burkina Faso.
Ce certificat est donné sous réserve de la consultation de la liste des produits manufacturés prévue par un arrêté."',
                'url' => 'https://eservices.envieau.gov.bf/login/P006',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 26,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            26 => 
            array (
                'id' => 27,
                'category_id' => 11,
                'title' => 'Certificat dorigine des marchandises co',
                'slug' => 'certificat-dorigine-des-marchandises-co',
                'description' => 'Un Certificat d\'Origine est un document utilisé pour attester l\'origine des marchandises lors des exportations vers un pays donné',
                'url' => 'https://peb.bf/actes-administratifs/certificat-d-origine',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 27,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            27 => 
            array (
                'id' => 28,
                'category_id' => 4,
                'title' => 'Cil gestion de plainte et de déclaration',
                'slug' => 'cil-gestion-de-plainte-et-de-declaration',
                'description' => 'Plateforme permettant aux citoyens de déposer une plainte et aux responsables de traitement de faire leurs déclarations',
                'url' => 'https://plainte-declaration.cil.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 28,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            28 => 
            array (
                'id' => 29,
                'category_id' => 3,
                'title' => 'Classement categoriel d\'un eth',
                'slug' => 'classement-categoriel-dun-eth',
                'description' => 'Le classement catégoriel d’un établissement touristique d’hébergement consiste à attribuer des étoiles aux ETH afin d’augmenter leur affluence',
                'url' => 'https://eservices-mccat.gov.bf/autrexpeth-choisir',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 29,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            29 => 
            array (
                'id' => 30,
                'category_id' => 19,
                'title' => 'Classement de restaurants de tourisme',
                'slug' => 'classement-de-restaurants-de-tourisme',
                'description' => 'Le classement catégoriel d’un restaurant de tourisme consiste à attribuer des stickers afin d’augmenter leur affluence',
                'url' => 'https://eservices-mccat.gov.bf/classementrt-choisir',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 30,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-21 00:02:42',
            ),
            30 => 
            array (
                'id' => 31,
                'category_id' => 13,
                'title' => 'Déclaration dinteret et de patrimoine',
                'slug' => 'declaration-dinteret-et-de-patrimoine',
                'description' => 'La déclaration consiste à faire état de tous ses biens matériels et immatériels, ainsi ceux de ses personnes liées. Cette obligation concerne certains fonctions et emplois. Les personnes soumises à cette obligation déclarative sont des assujettis à la DIP',
                'url' => 'https://www.dip.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 31,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            31 => 
            array (
                'id' => 32,
                'category_id' => 6,
                'title' => 'Déclaration prealable d\'importation dpi',
                'slug' => 'declaration-prealable-dimportation-dpi',
            'description' => 'La Déclaration Préalable d’Importation (DPI) est une formalité accomplie  au sein du ministère en charge du commerce préalablement à toute opération d’importation de marchandises dont la valeur Free On Board (FOB) est supérieure ou égale à 500 000 FCFA . Il s’agit d’une déclaration d’intention d’importer tous les besoins d’inspections.',
                'url' => 'https://peb.bf/e-services/declaration-prealable-d-importation',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 32,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            32 => 
            array (
                'id' => 33,
                'category_id' => 18,
                'title' => 'Demande attestation de soumission au marche public',
                'slug' => 'demande-attestation-de-soumission-au-marche-public',
                'description' => 'Demande Attestation de Soumission au Marché Public du Ministère de la Fonction Publique du Travail et de la Sécurité Sociale du Burkina Faso',
                'url' => 'http://montravail.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 33,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            33 => 
            array (
                'id' => 34,
                'category_id' => 14,
                'title' => 'Demande daudiences a la primature',
                'slug' => 'demande-daudiences-a-la-primature',
                'description' => 'Le service en ligne de soumission et de suivi des audiences à la Primature du Burkina Faso',
                'url' => 'http://audience.primature.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 34,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            34 => 
            array (
                'id' => 35,
                'category_id' => 8,
                'title' => 'Demande d\'autorisation speciale d\'importation asi',
                'slug' => 'demande-dautorisation-speciale-dimportation-asi',
            'description' => 'Portail d\'Entrée au Burkina (PEB), regroupant l\'ensemble des procédures administratives du ministère en charge du commerce et de l\'artisanat.',
                'url' => 'https://www.peb.bf/actes-administratifs/autorisation-speciale-d-importation',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 35,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            35 => 
            array (
                'id' => 36,
                'category_id' => 15,
                'title' => 'Demande davis de conformite environnementale',
                'slug' => 'demande-davis-de-conformite-environnementale',
            'description' => 'La demande d’avis de conformité environnementale est une démarche administrative préalable exigée pour tout projet de développement (public ou privé) qui pourrait avoir un impact sur l’environnement. Cette procédure permet au promoteur du projet d’obtenir l’accord des autorités environnementales, avant d’engager la phase de réalisation.',
                'url' => 'https://sinadeve.envieau.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 36,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            36 => 
            array (
                'id' => 37,
                'category_id' => 9,
                'title' => 'Demande d\'avis de faisabilité environnementale',
                'slug' => 'demande-davis-de-faisabilite-environnementale',
            'description' => 'La demande d’avis de faisabilité environnementale est une démarche administrative préalable exigée pour tout projet de développement (public ou privé) qui pourrait avoir un impact sur l’environnement. Cette procédure permet au promoteur du projet d’obtenir l’accord des autorités environnementales, avant d’engager la phase de réalisation.',
                'url' => 'https://sinadeve.envieau.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 37,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-21 00:02:42',
            ),
            37 => 
            array (
                'id' => 38,
                'category_id' => 5,
                'title' => 'Demande de carte de travail',
                'slug' => 'demande-de-carte-de-travail',
                'description' => 'Ouvrir le servicesendRetourkeyboard_backspace',
                'url' => 'http://cartedetravail.anpe.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 38,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            38 => 
            array (
                'id' => 39,
                'category_id' => 12,
                'title' => 'Demande de carte professionnelle de commercant cpc',
                'slug' => 'demande-de-carte-professionnelle-de-commercant-cpc',
            'description' => 'Demande de carte professionnelle de commerçant (CPC)',
                'url' => 'https://www.peb.bf/e-services/carte-professionnelle-de-commercant',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 39,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            39 => 
            array (
                'id' => 40,
                'category_id' => 10,
                'title' => 'Demande de création d\'entreprises pour les personnes morales ou physiques',
                'slug' => 'demande-de-creation-dentreprises-pour-les-personnes-morales-ou-physiques',
                'description' => 'Demande de création d\'entreprises pour les personnes morales ou physiques',
                'url' => 'https://creerentreprise.me.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 40,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-21 00:02:42',
            ),
            40 => 
            array (
                'id' => 41,
                'category_id' => 20,
                'title' => 'Demande de dispense du snd',
                'slug' => 'demande-de-dispense-du-snd',
                'description' => 'Il permet à tout usager répondant aux conditions de dispense du SND d\'effectuer sa demande de certificat en ligne',
                'url' => 'http://dispense.snd.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 41,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            41 => 
            array (
                'id' => 42,
                'category_id' => 2,
                'title' => 'Demande de foner',
                'slug' => 'demande-de-foner',
            'description' => '"Le FONER (Fonds National pour l’Éducation et la Recherche) est un mécanisme de soutien financier mis en place par l’État burkinabè pour aider les étudiants de l’enseignement supérieur à couvrir leurs frais de formation, principalement sous forme de prêt remboursable après les études."',
                'url' => 'https://foner.net/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 42,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            42 => 
            array (
                'id' => 43,
                'category_id' => 16,
                'title' => 'Demande de la carte grise pmc',
                'slug' => 'demande-de-la-carte-grise-pmc',
                'description' => 'Ouvrir le servicesendRetourkeyboard_backspace',
                'url' => 'http://pmc.transports.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 43,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            43 => 
            array (
                'id' => 44,
                'category_id' => 17,
                'title' => 'Demande de laissez passer des vehicules de letat',
                'slug' => 'demande-de-laissez-passer-des-vehicules-de-letat',
                'description' => 'Il s\'agit de la délivrance d\'un document permettant aux véhicules de l\'Etat d\'être mis en circulation hors heures réglementaires',
                'url' => 'https://www.asce-lc.bf/lp',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 44,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            44 => 
            array (
                'id' => 45,
                'category_id' => 7,
                'title' => 'Demande de lattestation de marche publics',
                'slug' => 'demande-de-lattestation-de-marche-publics',
                'description' => 'Demande de l’attestation de marché publics',
                'url' => 'http://marchespublics.anpe.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 45,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            45 => 
            array (
                'id' => 46,
                'category_id' => 1,
                'title' => 'Demande de lattestation de soumission aux marches publics',
                'slug' => 'demande-de-lattestation-de-soumission-aux-marches-publics',
                'description' => 'Cette prestation consiste à l’établissement d’une attestation de soumission aux marchés publics de l’État au profit d’une entreprise sur la base de sa fiche de déclaration annuelle du personnel et la présentation de sa situation cotisante à jour et faire preuve de l’établissement des cartes de travail pour son personnel.',
                'url' => 'https://attestation.anpe.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 46,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            46 => 
            array (
                'id' => 47,
                'category_id' => 11,
                'title' => 'Demande de partenariat',
                'slug' => 'demande-de-partenariat',
                'description' => 'Ouvrir le servicesendRetourkeyboard_backspace',
                'url' => 'http://partenariat.jeunesse.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 47,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            47 => 
            array (
                'id' => 48,
                'category_id' => 4,
                'title' => 'Demande detude de sols et fondations',
                'slug' => 'demande-detude-de-sols-et-fondations',
                'description' => 'Plateforme qui permet le dépôt et le traitement des demandes d\'étude de sols et fondations.',
                'url' => 'https://www.dsat.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 48,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            48 => 
            array (
                'id' => 49,
                'category_id' => 3,
                'title' => 'Demande en ligne de prestations anptic',
                'slug' => 'demande-en-ligne-de-prestations-anptic',
                'description' => 'Permet aux structures publiques de soumettre des demandes de prestation informatiques auprès de l\'ANPTIC.',
                'url' => 'https://convention.anptic.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 49,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            49 => 
            array (
                'id' => 50,
                'category_id' => 19,
                'title' => 'Demande etats civil',
                'slug' => 'demande-etats-civil',
                'description' => 'Ouvrir le servicesendRetourkeyboard_backspace',
                'url' => 'http://services-etatcivil.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 50,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            50 => 
            array (
                'id' => 51,
                'category_id' => 13,
                'title' => 'Dian',
                'slug' => 'dian',
                'description' => 'Dossiers Individuels des Archives Numérisées',
                'url' => 'http://dian.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 51,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            51 => 
            array (
                'id' => 52,
                'category_id' => 6,
                'title' => 'Digicop',
                'slug' => 'digicop',
                'description' => 'Plateforme permettant d\'assurer le contrôle de la présence des agents publics',
                'url' => 'https://digicop.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 52,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            52 => 
            array (
                'id' => 53,
                'category_id' => 18,
                'title' => 'DSAT : Demande ou Suspension d\'Agrément Technique BTP',
                'slug' => 'dsat-demande-ou-suspension-dagrement-technique-btp',
                'description' => 'Plateforme qui permet le dépôt et le traitement des agréments techniques en BTP.',
                'url' => 'https://www.dsat.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 53,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-21 00:02:42',
            ),
            53 => 
            array (
                'id' => 54,
                'category_id' => 14,
                'title' => 'E actes rccm',
                'slug' => 'e-actes-rccm',
            'description' => 'plateforme de demande et de délivrance en ligne des actes dérivés du Registre du Commerce et du Crédit Mobilier (RCCM)',
                'url' => 'https://www.e-actes-rccm.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 54,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            54 => 
            array (
                'id' => 55,
                'category_id' => 8,
                'title' => 'E casierjudiciaire',
                'slug' => 'e-casierjudiciaire',
                'description' => 'Plateforme numérique  qui permet de demander, payer, traiter et obtenir en ligne le bulletin n° 3 du casier judiciaire, de manière simple, rapide et sécurisée',
                'url' => 'https://ecasier-judiciaire.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 55,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            55 => 
            array (
                'id' => 56,
                'category_id' => 15,
                'title' => 'E Certificat nationalite',
                'slug' => 'e-certificat-nationalite',
                'description' => 'Le e-Certificat est une plateforme numérique qui permet de demander en ligne, payer, suivre et obtenir rapidement et en toute sécurité le certificat de nationalité, sans se déplacer',
                'url' => 'https://ecertificat-nationalite.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 56,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            56 => 
            array (
                'id' => 57,
                'category_id' => 9,
                'title' => 'E concours pro',
                'slug' => 'e-concours-pro',
                'description' => 'Cette plateforme permet aux candidats aux concours professionnels de la fonction publique de s\'inscrire en ligne via une plateforme internet dénommée "e-Concours-pro"',
                'url' => 'https://www.econcours-pro.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 57,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            57 => 
            array (
                'id' => 58,
                'category_id' => 5,
                'title' => 'E gratuite des soins',
                'slug' => 'e-gratuite-des-soins',
                'description' => 'La Plateforme de gestion des mesures de gratuité des soins du Burkina Faso',
                'url' => 'http://e-sante.gov.bf:8080/gratuitedessoins/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 58,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            58 => 
            array (
                'id' => 59,
                'category_id' => 12,
                'title' => 'E permis communiquer',
                'slug' => 'e-permis-communiquer',
            'description' => 'Plateforme permettant de délivrer le permis de communiquer (document administratif qui autorise une personne à rendre visite à un détenu incarcéré dans un établissement pénitentiaire. Il existe différents types de permis, chacun ayant des conditions et une durée de validité spécifiques).',
                'url' => 'https://e-permis-communiquer.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 59,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            59 => 
            array (
                'id' => 60,
                'category_id' => 10,
                'title' => 'E protocole detat',
                'slug' => 'e-protocole-detat',
                'description' => 'Plateforme de demande de carte diplomatique et d\'accès aux salons officiels des aéroports de Ouagadougou et Bobo dioulasso',
                'url' => 'https://eprotocole-etat.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 60,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            60 => 
            array (
                'id' => 61,
                'category_id' => 20,
                'title' => 'E recrutement',
                'slug' => 'e-recrutement',
                'description' => 'Plateforme web de dépôt, de suivi et de vérification de dossier en ligne pour les recrutements dans les Forces Armées Nationales.',
                'url' => 'https://erecrutement.defense.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 61,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            61 => 
            array (
                'id' => 62,
                'category_id' => 2,
                'title' => 'E siao',
                'slug' => 'e-siao',
                'description' => 'Achat de billet et réservation de Stand pour exposants durant le SIAO : Salon International de l\'Artisanat de Ouagadougou.',
                'url' => 'https://esiao.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 62,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            62 => 
            array (
                'id' => 63,
                'category_id' => 16,
                'title' => 'E sita',
                'slug' => 'e-sita',
                'description' => 'Plateforme de dépôt de plaintes en cas de conflit entre un employeur et l’employé',
                'url' => 'http://inspection-du-travail.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 63,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            63 => 
            array (
                'id' => 64,
                'category_id' => 17,
                'title' => 'E traduction',
                'slug' => 'e-traduction',
                'description' => 'Plateforme de demande de traduction des actes de l\'Etat civil et acte divers',
                'url' => 'https://etraduction.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 64,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            64 => 
            array (
                'id' => 65,
                'category_id' => 7,
                'title' => 'Ebulletin',
                'slug' => 'ebulletin',
                'description' => 'Mise en ligne du bulletin de salaire',
                'url' => 'https://ebulletin.finances.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 65,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            65 => 
            array (
                'id' => 66,
                'category_id' => 1,
                'title' => 'Edac',
                'slug' => 'edac',
                'description' => 'Demande en ligne d\'actes de carrière',
                'url' => 'https://www.edac.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 66,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            66 => 
            array (
                'id' => 67,
                'category_id' => 11,
                'title' => 'Edocument',
                'slug' => 'edocument',
                'description' => 'Plateforme de délivrance des quitus fiscaux à toutes personnes qui le souhaitent',
                'url' => 'https://dgi.bf/edocument/accueil',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 67,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            67 => 
            array (
                'id' => 68,
                'category_id' => 4,
                'title' => 'Endos bf',
                'slug' => 'endos-bf',
                'description' => 'Entrepôt de données sanitaires du Burkina Faso',
                'url' => 'https://burkina.dhis2.org/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 68,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            68 => 
            array (
                'id' => 69,
                'category_id' => 3,
                'title' => 'Esintax',
                'slug' => 'esintax',
                'description' => '"eSINTAX est constitué des espaces suivants:
1. espace des entreprises: pour les entreprises en vue de télétransmettre leurs déclarations et leurs états financiers ainsi que d\'effectuer leurs paiements des impôts et taxes et demandes des services en ligne
2. espace réservé aux banques: cet espace permet aux banques de valider les comptes bancaires des usagers de la plateforme eSINTAX et de traiter les ordres de paiements émis par ceux-ci;
3. espace experts comptables: cet espace permet aux experts comptables de donner des avis sur les états financiers des contribuables;
4. espace DGI: cet espace est réservé aux agents publics affectés à la DGI
5. un API pour les paiements mobiles est disponible
6. un API pour les paiements pour faciliter l\'automatisation du traitement des ordres de paiements au niveau des banques
7. un API pour les demandes ASF"',
                'url' => 'https://esintax.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 69,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            69 => 
            array (
                'id' => 70,
                'category_id' => 19,
                'title' => 'Etimbre',
                'slug' => 'etimbre',
                'description' => '"plateforme d\'achat et d\'oblitération des timbres fiscaux de la Direction générale des impôts: la plateforme permet aux usagers particuliers et entreprises d\'acquérir des timbres fiscaux en ligne
Il permet aux agents de l\'administration publique d\'oblitérer les timbres fiscaux afin qu\'ils ne soient pas réutilisés par son usage"',
                'url' => 'https://etimbre.dgi.bf/home',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 70,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            70 => 
            array (
                'id' => 71,
                'category_id' => 13,
                'title' => 'Etitre 2',
                'slug' => 'etitre-2',
                'description' => 'Plateforme de délivrance des titres de jouissance au profit des acquéreurs des terrains des promoteurs immobiliers',
                'url' => 'http://etitre2.dgi.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 71,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            71 => 
            array (
                'id' => 72,
                'category_id' => 6,
                'title' => 'Evisa',
                'slug' => 'evisa',
                'description' => 'Ce système permet à toutes personnes voulant se rendre au burkina  et assujeti au visa de faire la demande de visa et de payer les frais en ligne. Les postulants peuvent obtenir leur visa par voie électronique en fournissant les informations nécessaires. Le processus de traitement se fait également en ligne',
                'url' => 'https://www.visaburkina.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 72,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            72 => 
            array (
                'id' => 73,
                'category_id' => 18,
                'title' => 'Faso arzeka application citoyenne',
                'slug' => 'faso-arzeka-application-citoyenne',
                'description' => 'Cette procédure permet aux usagers de payer leurs  droits et des taxes de douanes',
                'url' => 'https://my.fasoarzeka.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 73,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            73 => 
            array (
                'id' => 74,
                'category_id' => 14,
                'title' => 'Faso e education',
                'slug' => 'faso-e-education',
                'description' => 'Site de contenuspédagogique destinée aux élèves, aux enseignants, aux encadreurs pédagogiques,
 aux parents d\'élèves... 
du préscolaire, du primaire, du post primaire,
 du secondaire et de l\'Education Non Formelle du Burkina Faso',
                'url' => 'https://fasoeducation.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 74,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            74 => 
            array (
                'id' => 75,
                'category_id' => 8,
                'title' => 'Fasoranana',
                'slug' => 'fasoranana',
            'description' => 'La création d’une plateforme de commerce en ligne (marché virtuel – marketplace) est un projet de développement de site internet dont l’objectif sera de vendre ou d’acheter des produits et / ou des services.',
                'url' => 'https://fasoranana.com/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 75,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-23 21:26:45',
            ),
            75 => 
            array (
                'id' => 76,
                'category_id' => 15,
                'title' => 'Fiche de voyage',
                'slug' => 'fiche-de-voyage',
                'description' => 'Elle permet au passager de remplir les formalités de Police d\'Immigration',
                'url' => 'https://fichedevoyage.gov.bf/',
                'source_file' => NULL,
                'is_active' => 1,
                'is_featured' => 0,
                'order' => 76,
                'created_at' => '2026-02-20 19:37:36',
                'updated_at' => '2026-02-21 00:02:42',
            ),
            76 => 
            array (
                'id' => 77,
                'category_id' => 9,
                'title' => 'Fichier national rccm',
                'slug' => 'fichier-national-rccm',
            'description' => 'Le Fichier National du Registre de Commerce et du Crédit Mobilier créée dans le but d\'archiver, de centraliser et de rendre accessibles au public des informations contenues dans les Registres du Commerce et du Crédit Mobilier (RCCM) immatriculés au Burkina Faso.
Cette plateforme permet la recherche et la consultation en ligne des documents officiels des entreprises immatriculées à la Maison de l\'Entreprise du Burkina Faso .',
            'url' => 'https://fichiernationalrccm.bf/',
            'source_file' => NULL,
            'is_active' => 1,
            'is_featured' => 0,
            'order' => 77,
            'created_at' => '2026-02-20 19:37:36',
            'updated_at' => '2026-02-23 21:26:45',
        ),
        77 => 
        array (
            'id' => 78,
            'category_id' => 5,
            'title' => 'Frsit',
            'slug' => 'frsit',
        'description' => 'Le FRSIT (Forum de la Recherche Scientifique et des Innovations Technologiques) est un événement national biennal au Burkina Faso qui met en valeur la recherche scientifique et les innovations technologiques pour promouvoir le développement du pays. La plateforme en ligne du FRSIT permet aux candidats de déposer leurs dossiers pour participer à la compétition.',
            'url' => 'https://frsit.campusfaso.bf/',
            'source_file' => NULL,
            'is_active' => 1,
            'is_featured' => 0,
            'order' => 78,
            'created_at' => '2026-02-20 19:37:36',
            'updated_at' => '2026-02-23 21:26:45',
        ),
        78 => 
        array (
            'id' => 79,
            'category_id' => 12,
            'title' => 'Hebergement campusfaso',
            'slug' => 'hebergement-campusfaso',
            'description' => '"La plateforme hebergement.campusfaso.bf est un espace en ligne mis à la disposition des étudiants pour leur permettre de soumettre une demande d’hébergement dans les cités ou résidences universitaires. Elle s’adresse principalement aux étudiants inscrits dans les établissements d’enseignement supérieur situés à Ouagadougou, Koudougou et Bobo-Dioulasso."',
            'url' => 'http://hebergement.campusfaso.bf/',
            'source_file' => NULL,
            'is_active' => 1,
            'is_featured' => 0,
            'order' => 79,
            'created_at' => '2026-02-20 19:37:36',
            'updated_at' => '2026-02-23 21:26:45',
        ),
        79 => 
        array (
            'id' => 80,
            'category_id' => 10,
            'title' => 'Helpdesk anptic',
            'slug' => 'helpdesk-anptic',
            'description' => 'Plateforme de gestion des incidents',
            'url' => 'https://helpdesk.gov.bf/',
            'source_file' => NULL,
            'is_active' => 1,
            'is_featured' => 0,
            'order' => 80,
            'created_at' => '2026-02-20 19:37:36',
            'updated_at' => '2026-02-23 21:26:45',
        ),
        80 => 
        array (
            'id' => 81,
            'category_id' => 20,
            'title' => 'Inscription a loperation permis de conduire',
            'slug' => 'inscription-a-loperation-permis-de-conduire',
            'description' => 'Inscription à l’Opération Permis de Conduire',
            'url' => 'http://opc.jeunesse.gov.bf/',
            'source_file' => NULL,
            'is_active' => 1,
            'is_featured' => 0,
            'order' => 81,
            'created_at' => '2026-02-20 19:37:36',
            'updated_at' => '2026-02-23 21:26:45',
        ),
        81 => 
        array (
            'id' => 82,
            'category_id' => 2,
            'title' => 'Inscription enafa',
            'slug' => 'inscription-enafa',
            'description' => 'Ouvrir le servicesendRetourkeyboard_backspace',
            'url' => 'https://inscriptions-enafa.gov.bf/',
            'source_file' => NULL,
            'is_active' => 1,
            'is_featured' => 0,
            'order' => 82,
            'created_at' => '2026-02-20 19:37:36',
            'updated_at' => '2026-02-23 21:26:45',
        ),
        82 => 
        array (
            'id' => 83,
            'category_id' => 16,
            'title' => 'Intranet mcrp',
            'slug' => 'intranet-mcrp',
            'description' => 'Une plateforme web de travail collaboratif du personnel du ministère de la communication et des relations avec le parlement et du public invité à voir les informations publiques.',
            'url' => 'http://www.mcrpintranet.gov.bf/',
            'source_file' => NULL,
            'is_active' => 1,
            'is_featured' => 0,
            'order' => 83,
            'created_at' => '2026-02-20 19:37:36',
            'updated_at' => '2026-02-23 21:26:45',
        ),
        83 => 
        array (
            'id' => 84,
            'category_id' => 17,
            'title' => 'Jobf',
            'slug' => 'jobf',
            'description' => 'Plateforme de publication, d’achat, d’abonnement et d’insertion au Journal officiel.',
            'url' => 'https://www.jobf.gov.bf/',
            'source_file' => NULL,
            'is_active' => 1,
            'is_featured' => 0,
            'order' => 84,
            'created_at' => '2026-02-20 19:37:36',
            'updated_at' => '2026-02-23 21:26:45',
        ),
        84 => 
        array (
            'id' => 85,
            'category_id' => 7,
            'title' => 'e-formation',
            'slug' => 'e-formation',
        'description' => 'La plateforme d’autoformation en ligne des agents de l’Etat (PALAE) est un outil souple, dynamique et autonome de formation au service de l’agent public de l’Etat',
            'url' => 'http://eformation.gov.bf/',
            'source_file' => NULL,
            'is_active' => 1,
            'is_featured' => 0,
            'order' => 85,
            'created_at' => '2026-02-20 19:37:36',
            'updated_at' => '2026-02-21 00:02:42',
        ),
        85 => 
        array (
            'id' => 86,
            'category_id' => 1,
            'title' => 'Legiburkina',
            'slug' => 'legiburkina',
        'description' => 'Plateforme de diffusion de la règle de droit ( lois, décrets, arrêtés …)',
            'url' => 'https://www.legiburkina.gov.bf/',
            'source_file' => NULL,
            'is_active' => 1,
            'is_featured' => 0,
            'order' => 86,
            'created_at' => '2026-02-20 19:37:36',
            'updated_at' => '2026-02-23 21:26:45',
        ),
        86 => 
        array (
            'id' => 87,
            'category_id' => 11,
            'title' => 'Licence d\'entrepreneur de spectacle',
            'slug' => 'licence-dentrepreneur-de-spectacle',
            'description' => 'La licence d’entrepreneur de spectacles est un document administratif qui permet d’organiser ou de diffuser des spectacles vivants',
            'url' => 'https://eservices-mccat.gov.bf/login',
            'source_file' => NULL,
            'is_active' => 1,
            'is_featured' => 0,
            'order' => 87,
            'created_at' => '2026-02-20 19:37:36',
            'updated_at' => '2026-02-21 00:02:42',
        ),
        87 => 
        array (
            'id' => 88,
            'category_id' => 4,
            'title' => 'Nnumero issn',
            'slug' => 'nnumero-issn',
        'description' => 'Un ISSN (International Standard Serial Numbers) est un numéro international normalisé des publications en série. Il s\'agit d\'un code unique attribués aux publications en série, telles que les journaux, les magazines, les revues scientifiques et autres périodiques. Ce code permet une identification précise et sans ambiguïté de ces publications à l\'échelle internationale.
L\'attribution des ISSN est gérée par un centre international. Au Burkina, les éditeurs de publications en série doivent faire une demande d\'ISSN auprès de la Bibliothèque Nationale.
Cette procédure a pour but de dématérialiser la demande de numéro ISSN au niveau national',
        'url' => 'https://eservices-mccat.gov.bf/choix-demande-issn',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 88,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    88 => 
    array (
        'id' => 89,
        'category_id' => 3,
        'title' => 'Numero de depot legal',
        'slug' => 'numero-de-depot-legal',
        'description' => 'Le dépôt légal est l’obligation faite à tout créateur ou producteur de procéder à l’enregistrement des productions nationales en vue de favoriser l’enrichissement du patrimoine national et son suivi',
        'url' => 'https://eservices-mccat.gov.bf/choix-depot-legal',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 89,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    89 => 
    array (
        'id' => 90,
        'category_id' => 19,
        'title' => 'Onef plateforme de publication des offres d\'emploi et de formation',
        'slug' => 'onef-plateforme-de-publication-des-offres-demploi-et-de-formation',
        'description' => 'Les structures sollicitent la publication de leurs offres  sur le site web. Les offres reçus des structures sont traitées et diffusées par l’ONEF sur son site www.onef.gov.bf',
        'url' => 'https://onef.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 90,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    90 => 
    array (
        'id' => 91,
        'category_id' => 13,
        'title' => 'Oun observatoire urbain national',
        'slug' => 'oun-observatoire-urbain-national',
        'description' => 'Une Plateforme en ligne permettant de renseigner et de diffuser les données de l’OUN-BF;
Elle va fournir des informations utiles pour la prise de décision en matière d\'urbanisme et de développement urbain, en se concentrant sur des thématiques telles que la démographie, les équipements, la mobilité, l\'environnement, le logement, le foncier et la gouvernance urbain.
L’Observatoire Urbain National du Burkina Faso a pour missions de suivre l’évolution des villes, d’évaluer et d’orienter les politiques urbaines à travers des indicateurs urbains.',
        'url' => 'https://www.oun.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 91,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    91 => 
    array (
        'id' => 92,
        'category_id' => 6,
        'title' => 'Paiement des droits de chancellerie',
        'slug' => 'paiement-des-droits-de-chancellerie',
        'description' => 'Permettre aux recipiendaires de s\'acquiter des droits de chancellerie liés aux décorations sans se déplacer',
        'url' => 'https://paiement.sgi-gcob.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 92,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-21 00:02:42',
    ),
    92 => 
    array (
        'id' => 93,
        'category_id' => 18,
        'title' => 'ePlainte',
        'slug' => 'eplainte',
        'description' => 'Plateforme permettant de recueillir et de traiter les plaintes, suggestions et satisfactions des usagers des services publics',
        'url' => 'https://eplainte.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 93,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-21 00:02:42',
    ),
    93 => 
    array (
        'id' => 94,
        'category_id' => 14,
        'title' => 'Plateforme de la diaspora',
        'slug' => 'plateforme-de-la-diaspora',
        'description' => 'Plateforme de demande d\'immatriculation et de carte consulaire',
        'url' => 'https://diaspora.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 94,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    94 => 
    array (
        'id' => 95,
        'category_id' => 8,
        'title' => 'Plateforme de retraite informatisee simplifiee et centralisee pour les actes prisca',
        'slug' => 'plateforme-de-retraite-informatisee-simplifiee-et-centralisee-pour-les-actes-prisca',
    'description' => 'Faciliter mon départ à la retraite avec la Plateforme de Retraite Informatisée, Simplifiée et Centralisée pour les Actes (PRISCA)',
        'url' => 'http://maretraite.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 95,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    95 => 
    array (
        'id' => 96,
        'category_id' => 15,
        'title' => 'Plateforme de suivi et evaluation des activites du ministere de la fonction publique',
        'slug' => 'plateforme-de-suivi-et-evaluation-des-activites-du-ministere-de-la-fonction-publique',
        'description' => 'Plateforme de suivi et évaluation des activités du ministère de la Fonction Publique',
        'url' => 'http://kolekt.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 96,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    96 => 
    array (
        'id' => 97,
        'category_id' => 9,
        'title' => 'Plateforme devaluation du personnel de ladministration publique burkinabe enotation',
        'slug' => 'plateforme-devaluation-du-personnel-de-ladministration-publique-burkinabe-enotation',
    'description' => 'Plateforme d\'évaluation du personnel de l\'administration publique burkinabè (eNotation)',
        'url' => 'http://enotation.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 97,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    97 => 
    array (
        'id' => 98,
        'category_id' => 5,
        'title' => 'e-concours-direct',
        'slug' => 'e-concours-direct',
        'description' => 'Cette plateforme permet aux candidats aux concours professionnels de la fonction publique de composer en ligne',
        'url' => 'https://www.econcours.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 98,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-21 00:02:42',
    ),
    98 => 
    array (
        'id' => 99,
        'category_id' => 12,
        'title' => 'Plateforme integree de gestion academique',
        'slug' => 'plateforme-integree-de-gestion-academique',
        'description' => '"La plateforme intégrée de gestion  académique est un système numérique destiné aux établissements d’enseignement supérieur pour gérer efficacement l’ensemble du parcours étudiant, de l’inscription à la diplomation. Elle prend en charge la gestion du système LMD, des volumes horaires, des notes, des emplois du temps, et des délibérations, tout en assurant la traçabilité et la transparence des données pédagogiques."',
        'url' => 'https://services.campusfaso.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 99,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    99 => 
    array (
        'id' => 100,
        'category_id' => 10,
        'title' => 'Plateforme mobile android pour les inscriptions en ligne',
        'slug' => 'plateforme-mobile-android-pour-les-inscriptions-en-ligne',
        'description' => 'Cette prestation permet aux candidats aux concours directs de la fonction publique de s\'inscrire en ligne via l\'application android',
        'url' => 'https://play.google.com/store/apps/details?id=bf.stgvap.econcours',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 100,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-21 00:02:42',
    ),
    100 => 
    array (
        'id' => 101,
        'category_id' => 20,
        'title' => 'Plateforme numerique youthconnekt burkina yc b',
        'slug' => 'plateforme-numerique-youthconnekt-burkina-yc-b',
        'description' => 'Cette plateforme permet aux jeunes d\'accéder aux opportunités d\'emploi, de stages, de formation et de participation citoyenne. Elle permet aussi aux jeunes de différents horizons d\'interagir',
        'url' => 'https://www.youthconnektburkina.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 101,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    101 => 
    array (
        'id' => 102,
        'category_id' => 2,
        'title' => 'Plateforme de demande de l’attestation de chômage',
        'slug' => 'plateforme-de-demande-de-lattestation-de-chomage',
        'description' => 'Plateforme de demande de l’attestation de chômage',
        'url' => 'http://montravail.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 102,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-21 00:02:42',
    ),
    102 => 
    array (
        'id' => 103,
        'category_id' => 16,
        'title' => 'Portail des e services en environnement eau et assainissement',
        'slug' => 'portail-des-e-services-en-environnement-eau-et-assainissement',
        'description' => 'Portail des e-services en Environnement, Eau et Assainissement',
        'url' => 'https://eservices.envieau.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 103,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    103 => 
    array (
        'id' => 104,
        'category_id' => 17,
        'title' => 'Rbe registre electronique des beneficiaires effectifs',
        'slug' => 'rbe-registre-electronique-des-beneficiaires-effectifs',
    'description' => 'Le site web du Registre Électronique des Bénéficiaires Effectifs (RBE) du Burkina Faso est une plateforme officielle mise en place par les autorités burkinabè pour centraliser et rendre accessibles les informations relatives aux bénéficiaires effectifs des personnes morales et structures juridiques enregistrées dans le pays.  Ce registre vise à renforcer la transparence financière, lutter contre le blanchiment de capitaux, le financement du terrorisme et à assurer la traçabilité de la propriété réelle des entreprises. Il permet aux entreprises de déclarer leurs bénéficiaires effectifs en ligne, conformément aux exigences de la loi burkinabè et aux normes internationales en matière de transparence.  Fonctionnalités principales :  Déclaration en ligne des bénéficiaires effectifs par les entreprises.  Consultation sécurisée des informations pour les autorités compétentes.  Guide d’utilisation, assistance et documents réglementaires.  Accès aux textes législatifs et réglementaires applicables.  Le site est conçu pour être simple d’utilisation, sécurisé et accessible à tous les utilisateurs concernés, notamment les entreprises, les professionnels du droit, les institutions financières, et les autorités de régulation.',
        'url' => 'https://rbe.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 104,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    104 => 
    array (
        'id' => 105,
        'category_id' => 7,
        'title' => 'Renouvellement autorisation d\'exploiter un ETH',
        'slug' => 'renouvellement-autorisation-dexploiter-un-eth',
        'description' => 'Le renouvellement de l’autorisation d’exploiter un établissement touristique d’hébergement est un document administratif qui permet au promoteur de poursuivre l’exploitation de son entreprise.',
        'url' => 'https://eservices-mccat.gov.bf/login',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 105,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-21 00:02:42',
    ),
    105 => 
    array (
        'id' => 106,
        'category_id' => 1,
        'title' => 'Renouvellement d\'autorisation d\'exploiter un ETL',
        'slug' => 'renouvellement-dautorisation-dexploiter-un-etl',
        'description' => 'Le renouvellement de l’autorisation d’exploiter un établissement touristique de loisirs ou de l’autorisation d’exploiter une succursale d’un établissement touristique de loisirs est un document administratif qui permet au promoteur de poursuivre l’exploitation de son entreprise',
        'url' => 'https://eservices-mccat.gov.bf/login',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 106,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-21 00:02:42',
    ),
    106 => 
    array (
        'id' => 107,
        'category_id' => 11,
        'title' => 'Renouvellement de lautorisation dexploiter un restaurant de tourisme rt',
        'slug' => 'renouvellement-de-lautorisation-dexploiter-un-restaurant-de-tourisme-rt',
        'description' => 'Le renouvellement de l’autorisation d’exploiter un restaurant de tourisme ou de l’autorisation d’exploiter une succursale d’un restaurant de tourisme est un document administratif qui permet au promoteur de poursuivre l’exploitation de son entreprise',
        'url' => 'https://eservices-mccat.gov.bf/autrexprt-choisir',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 107,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    107 => 
    array (
        'id' => 108,
        'category_id' => 4,
        'title' => 'Sadina',
        'slug' => 'sadina',
        'description' => 'Système d\'Accès aux Dossiers Individuels Numérisés des Agents',
        'url' => 'http://www.sadina.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 108,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    108 => 
    array (
        'id' => 109,
        'category_id' => 3,
        'title' => 'Secop',
        'slug' => 'secop',
        'description' => 'Système électronique de délivrance des pièces administratives de la commande publique. Facilite l\'accès aux services administratifs liés aux marchés publics à travers une plateforme numérique innovante, sécurisée et performante. Notre objectif est de réduire les délais de traitement et d\'améliorer la transparence des procédures.',
        'url' => 'https://secop.finances.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 109,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    109 => 
    array (
        'id' => 110,
        'category_id' => 19,
        'title' => 'Sigobs plateforme de gestion des bourses de lorientation et des affectation scolaire',
        'slug' => 'sigobs-plateforme-de-gestion-des-bourses-de-lorientation-et-des-affectation-scolaire',
        'description' => 'Permet aux candidats de postuler aux bourses scolaires et de les préselectionner par ordre de mérite',
        'url' => 'https://sigospb.formationpro.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 110,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    110 => 
    array (
        'id' => 111,
        'category_id' => 13,
        'title' => 'Sised',
        'slug' => 'sised',
    'description' => 'Le système Intégré de Suivi-Evaluation de la décentralisation (SISED) est une plateforme de collecte de données sur la décentralisation. les données de cette plateforme alimentent un portail web qui sert de vitrine d’information sur la décentralisation appelée infocentre de la décentralisation',
        'url' => 'http://www.sised.gov.bf/SISED-BF/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 111,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    111 => 
    array (
        'id' => 112,
        'category_id' => 6,
        'title' => 'SYCAD',
        'slug' => 'sycad',
        'description' => 'Plateforme de gestion complète des processus du cadastre, des domaines et du foncier.',
        'url' => 'https://sif.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 112,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-21 00:02:42',
    ),
    112 => 
    array (
        'id' => 113,
        'category_id' => 18,
        'title' => 'Sylep systeme en ligne des encheres publiques',
        'slug' => 'sylep-systeme-en-ligne-des-encheres-publiques',
        'description' => 'Système en ligne des enchères publiques',
        'url' => 'https://ventes-encheres.finances.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 113,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    113 => 
    array (
        'id' => 114,
        'category_id' => 14,
        'title' => 'Tengatopo',
        'slug' => 'tengatopo',
        'description' => 'Gestion des demandes de terrains et d’autorisations d’aménagements',
        'url' => 'https://www.tengatopo.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 114,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-21 00:02:42',
    ),
    114 => 
    array (
        'id' => 115,
        'category_id' => 8,
        'title' => 'Trhimo travaux routiers a haute intensite de main doeuvre',
        'slug' => 'trhimo-travaux-routiers-a-haute-intensite-de-main-doeuvre',
        'description' => 'Recrutement des brigadiers pour les travaux à haute intensité de mains d\'œuvre.',
        'url' => 'https://www.trhimo.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 115,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    115 => 
    array (
        'id' => 116,
        'category_id' => 15,
    'title' => 'Validation de la licence d\'opérateur de voyage et de tourisme (OVT)',
        'slug' => 'validation-de-la-licence-doperateur-de-voyage-et-de-tourisme-ovt',
        'description' => 'La validation de la licence d’une agence d’opérateur de voyages et de tourisme ou de la licence d’une succursale d’une agence d’opérateur de voyages et de tourisme permet au promoteur de poursuivre l’exploitation d’une entreprise créée à cet effet',
        'url' => 'https://eservices-mccat.gov.bf/login',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 116,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-21 00:02:42',
    ),
    116 => 
    array (
        'id' => 117,
        'category_id' => 9,
        'title' => 'Visa dexploitation de film',
        'slug' => 'visa-dexploitation-de-film',
        'description' => 'Le visa d’exploitation des films est un document administratif qui autorise un importateur ou un distributeur à exploiter des films dans le respect des bonnes mœurs',
        'url' => 'https://eservices-mccat.gov.bf/choix-depot-visa',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 117,
        'created_at' => '2026-02-20 19:37:36',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    117 => 
    array (
        'id' => 119,
        'category_id' => NULL,
        'title' => 'Attestation de travail',
        'slug' => 'attestation-de-travail',
        'description' => 'Ministère de la Fonction Publique du Travail et de la Sécurité Sociale du Burkina Faso
Demande Attestation de Travail',
        'url' => 'https://www.montravail.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 0,
        'created_at' => '2026-02-23 21:26:45',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    118 => 
    array (
        'id' => 120,
        'category_id' => NULL,
        'title' => 'La plateforme dautoformation en ligne des agents de letat palae est un outil souple dynamique et autonome de formation au service de lagent public de letat',
        'slug' => 'la-plateforme-dautoformation-en-ligne-des-agents-de-letat-palae-est-un-outil-souple-dynamique-et-autonome-de-formation-au-service-de-lagent-public-de-letat',
    'description' => 'La plateforme d’autoformation en ligne des agents de l’Etat (PALAE) est un outil souple, dynamique et autonome de formation au service de l’agent public de l’Etat',
        'url' => 'http://eformation.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 0,
        'created_at' => '2026-02-23 21:26:45',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    119 => 
    array (
        'id' => 121,
        'category_id' => NULL,
        'title' => 'Paiement des droits de chancellerie via mobilemoney',
        'slug' => 'paiement-des-droits-de-chancellerie-via-mobilemoney',
        'description' => 'Permettre aux recipiendaires de s\'acquiter des droits de chancellerie liés aux décorations sans se déplacer',
        'url' => 'https://paiement.sgi-gcob.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 0,
        'created_at' => '2026-02-23 21:26:45',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    120 => 
    array (
        'id' => 122,
        'category_id' => NULL,
        'title' => 'Plateforme de gestion des suggestions et des plaintes',
        'slug' => 'plateforme-de-gestion-des-suggestions-et-des-plaintes',
        'description' => 'Plateforme permettant de recueillir et de traiter les plaintes, suggestions et satisfactions des usagers des services publics',
        'url' => 'https://eplainte.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 0,
        'created_at' => '2026-02-23 21:26:45',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    121 => 
    array (
        'id' => 123,
        'category_id' => NULL,
        'title' => 'Plateforme d\'inscription de composition en ligne concours profesionnels de la fonction publique',
        'slug' => 'plateforme-dinscription-de-composition-en-ligne-concours-profesionnels-de-la-fonction-publique',
        'description' => 'Cette plateforme permet aux candidats aux concours professionnels de la fonction publique de composer en ligne',
        'url' => 'https://www.econcours.gov.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 0,
        'created_at' => '2026-02-23 21:26:45',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    122 => 
    array (
        'id' => 124,
        'category_id' => NULL,
        'title' => 'Plateforme mobile',
        'slug' => 'plateforme-mobile',
        'description' => 'Cette prestation permet aux candidats aux concours directs de la fonction publique de s\'inscrire en ligne via l\'application android',
        'url' => 'https://play.google.com/store/apps/details?id=bf.stgvap.econcours',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 0,
        'created_at' => '2026-02-23 21:26:45',
        'updated_at' => '2026-02-23 21:26:45',
    ),
    123 => 
    array (
        'id' => 125,
        'category_id' => NULL,
        'title' => 'Syc at d',
        'slug' => 'syc-at-d',
        'description' => 'Plateforme de gestion complète des processus du cadastre, des domaines et du foncier.',
        'url' => 'https://sif.bf/',
        'source_file' => NULL,
        'is_active' => 1,
        'is_featured' => 0,
        'order' => 0,
        'created_at' => '2026-02-23 21:26:45',
        'updated_at' => '2026-02-23 21:26:45',
    ),
));
        
        
    }
}