<?php

namespace Database\Seeders;

use App\Models\Structure;
use Illuminate\Database\Seeder;

class StructureSeeder extends Seeder
{
    public function run(): void
    {
        $structures = [
            // Institutions
            [
                'nom' => 'Présidence du Faso',
                'sigle' => null,
                'slug' => 'presidence',
                'type' => 'institution',
                'description' => 'La Présidence du Faso est l\'institution suprême du Burkina Faso.',
                'adresse' => 'Palais de Kosyam, Ouagadougou',
                'telephone' => '+226 25 30 60 00',
                'email' => 'contact@presidence.gov.bf',
                'site_web' => 'https://www.presidence.gov.bf',
                'horaires' => 'Lundi - Vendredi: 7h30 - 12h30, 15h00 - 17h30',
                'ordre' => 1,
            ],
            [
                'nom' => 'Assemblée Nationale',
                'sigle' => null,
                'slug' => 'assemblee',
                'type' => 'institution',
                'description' => 'L\'Assemblée Nationale est la chambre unique du Parlement burkinabè.',
                'adresse' => 'Avenue de l\'Assemblée Nationale, Ouagadougou',
                'telephone' => '+226 25 30 70 00',
                'email' => 'contact@assemblee.gov.bf',
                'site_web' => 'https://www.assemblee.gov.bf',
                'ordre' => 2,
            ],
            [
                'nom' => 'Primature',
                'sigle' => null,
                'slug' => 'primature',
                'type' => 'institution',
                'description' => 'La Primature coordonne l\'action gouvernementale.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 80 00',
                'email' => 'contact@primature.gov.bf',
                'site_web' => 'https://www.primature.gov.bf',
                'ordre' => 3,
            ],

            // Ministères
            [
                'nom' => 'Ministère de l\'Administration Territoriale, de la Décentralisation et de la Sécurité',
                'sigle' => 'MATDS',
                'slug' => 'matds',
                'type' => 'ministere',
                'description' => 'Chargé de l\'administration territoriale, de la décentralisation et de la sécurité.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 41 00',
                'email' => 'contact@matds.gov.bf',
                'ordre' => 1,
            ],
            [
                'nom' => 'Ministère des Affaires Étrangères, de la Coopération régionale et des Burkinabè de l\'Extérieur',
                'sigle' => 'MAECRBE',
                'slug' => 'maecrbe',
                'type' => 'ministere',
                'description' => 'Chargé des relations internationales et de la coopération.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 42 00',
                'email' => 'contact@maecrbe.gov.bf',
                'ordre' => 2,
            ],
            [
                'nom' => 'Ministère de l\'Économie, des Finances et de la Prospective',
                'sigle' => 'MEFP',
                'slug' => 'mefp',
                'type' => 'ministere',
                'description' => 'Chargé de la politique économique et financière du pays.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 43 00',
                'email' => 'contact@mefp.gov.bf',
                'ordre' => 3,
            ],
            [
                'nom' => 'Ministère de la Justice, des Droits humains et de la Citoyenneté',
                'sigle' => 'MJDHRC',
                'slug' => 'mjdhrc',
                'type' => 'ministere',
                'description' => 'Chargé de l\'administration de la justice et des droits humains.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 44 00',
                'email' => 'contact@justice.gov.bf',
                'ordre' => 4,
            ],
            [
                'nom' => 'Ministère de l\'Éducation nationale, de l\'Alphabétisation et de la Promotion des Langues nationales',
                'sigle' => 'MENAPLN',
                'slug' => 'menapln',
                'type' => 'ministere',
                'description' => 'Chargé de l\'éducation nationale et de l\'alphabétisation.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 45 00',
                'email' => 'contact@education.gov.bf',
                'ordre' => 5,
            ],
            [
                'nom' => 'Ministère de la Santé et de l\'Hygiène publique',
                'sigle' => 'MSHP',
                'slug' => 'mshp',
                'type' => 'ministere',
                'description' => 'Chargé de la santé publique et de l\'hygiène.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 46 00',
                'email' => 'contact@sante.gov.bf',
                'ordre' => 6,
            ],
            [
                'nom' => 'Ministère de l\'Agriculture, des Ressources animales et halieutiques',
                'sigle' => 'MARAH',
                'slug' => 'marah',
                'type' => 'ministere',
                'description' => 'Chargé de l\'agriculture et des ressources animales.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 47 00',
                'email' => 'contact@agriculture.gov.bf',
                'ordre' => 7,
            ],
            [
                'nom' => 'Ministère de l\'Environnement, de l\'Energie, des Eaux et de l\'Assainissement',
                'sigle' => 'MEEEA',
                'slug' => 'meeea',
                'type' => 'ministere',
                'description' => 'Chargé de l\'environnement et des ressources en eau.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 48 00',
                'email' => 'contact@environnement.gov.bf',
                'ordre' => 8,
            ],
            [
                'nom' => 'Ministère des Infrastructures et du Désenclavement',
                'sigle' => 'MID',
                'slug' => 'mid',
                'type' => 'ministere',
                'description' => 'Chargé des infrastructures et des transports.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 49 00',
                'email' => 'contact@infrastructures.gov.bf',
                'ordre' => 9,
            ],
            [
                'nom' => 'Ministère du Commerce, de l\'Industrie et de l\'Artisanat',
                'sigle' => 'MCIA',
                'slug' => 'mcia',
                'type' => 'ministere',
                'description' => 'Chargé du commerce, de l\'industrie et de l\'artisanat.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 50 00',
                'email' => 'contact@commerce.gov.bf',
                'ordre' => 10,
            ],
            [
                'nom' => 'Ministère de la Fonction publique, du Travail et de la Protection sociale',
                'sigle' => 'MFPTPS',
                'slug' => 'mfptps',
                'type' => 'ministere',
                'description' => 'Chargé de la fonction publique et du travail.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 51 00',
                'email' => 'contact@fonctionpublique.gov.bf',
                'ordre' => 11,
            ],
            [
                'nom' => 'Ministère de la Communication, de la Culture, des Arts et du Tourisme',
                'sigle' => 'MCCAT',
                'slug' => 'mccat',
                'type' => 'ministere',
                'description' => 'Chargé de la communication et de la culture.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 52 00',
                'email' => 'contact@communication.gov.bf',
                'ordre' => 12,
            ],
            [
                'nom' => 'Ministère de la Femme, de la Solidarité nationale, de la Famille et de l\'Action humanitaire',
                'sigle' => 'MFSNFAH',
                'slug' => 'mfsnfah',
                'type' => 'ministere',
                'description' => 'Chargé des questions liées à la femme et à la famille.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 53 00',
                'email' => 'contact@femme.gov.bf',
                'ordre' => 13,
            ],
            [
                'nom' => 'Ministère de la Jeunesse et des Sports',
                'sigle' => 'MJS',
                'slug' => 'mjs',
                'type' => 'ministere',
                'description' => 'Chargé de la jeunesse et des sports.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 54 00',
                'email' => 'contact@jeunesse.gov.bf',
                'ordre' => 14,
            ],
            [
                'nom' => 'Ministère du Numérique, de la Transition digitale et de la Modernisation de l\'Administration',
                'sigle' => 'MNTDMA',
                'slug' => 'mntdma',
                'type' => 'ministere',
                'description' => 'Chargé du numérique et de la modernisation de l\'administration.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 55 00',
                'email' => 'contact@numerique.gov.bf',
                'ordre' => 15,
            ],

            // Directions
            [
                'nom' => 'Direction Générale de la Police nationale',
                'sigle' => 'DGPN',
                'slug' => 'dgpn',
                'type' => 'direction',
                'description' => 'Direction chargée de la police nationale.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 60 00',
                'email' => 'contact@police.gov.bf',
                'ordre' => 1,
            ],
            [
                'nom' => 'Direction Générale des Impôts',
                'sigle' => 'DGI',
                'slug' => 'dgi',
                'type' => 'direction',
                'description' => 'Direction chargée de la fiscalité.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 61 00',
                'email' => 'contact@impots.gov.bf',
                'ordre' => 2,
            ],
            [
                'nom' => 'Direction Générale des Douanes',
                'sigle' => 'DGD',
                'slug' => 'dgd',
                'type' => 'direction',
                'description' => 'Direction chargée des douanes.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 62 00',
                'email' => 'contact@douanes.gov.bf',
                'ordre' => 3,
            ],
            [
                'nom' => 'Centre National de la Recherche Scientifique et Technologique',
                'sigle' => 'CNRST',
                'slug' => 'cnrst',
                'type' => 'direction',
                'description' => 'Centre de recherche scientifique et technologique.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 63 00',
                'email' => 'contact@cnrst.gov.bf',
                'ordre' => 4,
            ],
            [
                'nom' => 'Office National d\'Identification',
                'sigle' => 'ONI',
                'slug' => 'oni',
                'type' => 'direction',
                'description' => 'Chargé de l\'identification des citoyens.',
                'adresse' => 'Ouagadougou',
                'telephone' => '+226 25 30 64 00',
                'email' => 'contact@oni.gov.bf',
                'ordre' => 5,
            ],
        ];

        foreach ($structures as $structure) {
            Structure::create($structure);
        }
    }
}
