<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SubcategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('subcategories')->delete();
        
        \DB::table('subcategories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 1,
                'name' => 'Activités commerciales',
                'slug' => 'activites-commerciales',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 1,
                'name' => 'Concurrence',
                'slug' => 'concurrence',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 1,
                'name' => 'Création d\'entreprise',
                'slug' => 'creation-dentreprise',
                'description' => NULL,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 2,
                'name' => 'Communication',
                'slug' => 'communication',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 2,
                'name' => 'Communication audio-visuelle',
                'slug' => 'communication-audio-visuelle',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 2,
                'name' => 'TIC',
                'slug' => 'tic',
                'description' => NULL,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 3,
                'name' => 'Commandes publiques',
                'slug' => 'commandes-publiques',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 3,
                'name' => 'Comptabilité publique',
                'slug' => 'comptabilite-publique',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 3,
                'name' => 'Dépenses publiques',
                'slug' => 'depenses-publiques',
                'description' => NULL,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            9 => 
            array (
                'id' => 10,
                'category_id' => 3,
                'name' => 'Impôts et taxes',
                'slug' => 'impots-et-taxes',
                'description' => NULL,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            10 => 
            array (
                'id' => 11,
                'category_id' => 3,
                'name' => 'Prêts/aides/dons',
                'slug' => 'pretsaidesdons',
                'description' => NULL,
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            11 => 
            array (
                'id' => 12,
                'category_id' => 4,
                'name' => 'Femme et Genre',
                'slug' => 'femme-et-genre',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            12 => 
            array (
                'id' => 13,
                'category_id' => 4,
                'name' => 'Services sociaux',
                'slug' => 'services-sociaux',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            13 => 
            array (
                'id' => 14,
                'category_id' => 5,
                'name' => 'Emploi',
                'slug' => 'emploi',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            14 => 
            array (
                'id' => 15,
                'category_id' => 5,
                'name' => 'Formation professionnelle',
                'slug' => 'formation-professionnelle',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            15 => 
            array (
                'id' => 16,
                'category_id' => 5,
                'name' => 'Administration du travail',
                'slug' => 'administration-du-travail',
                'description' => NULL,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            16 => 
            array (
                'id' => 17,
                'category_id' => 5,
                'name' => 'Protection sociale',
                'slug' => 'protection-sociale',
                'description' => NULL,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            17 => 
            array (
                'id' => 18,
                'category_id' => 6,
                'name' => 'Promotion de la justice',
                'slug' => 'promotion-de-la-justice',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            18 => 
            array (
                'id' => 19,
                'category_id' => 6,
                'name' => 'Promotion des droits humains',
                'slug' => 'promotion-des-droits-humains',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            19 => 
            array (
                'id' => 20,
                'category_id' => 7,
                'name' => 'Bourses d\'études',
                'slug' => 'bourses-detudes',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            20 => 
            array (
                'id' => 21,
                'category_id' => 7,
                'name' => 'Enseignement',
                'slug' => 'enseignement',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            21 => 
            array (
                'id' => 22,
                'category_id' => 7,
                'name' => 'Formation',
                'slug' => 'formation',
                'description' => NULL,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            22 => 
            array (
                'id' => 23,
                'category_id' => 7,
                'name' => 'Recherche scientifique',
                'slug' => 'recherche-scientifique',
                'description' => NULL,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            23 => 
            array (
                'id' => 24,
                'category_id' => 8,
                'name' => 'Santé humaine',
                'slug' => 'sante-humaine',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            24 => 
            array (
                'id' => 25,
                'category_id' => 9,
                'name' => 'Logistique',
                'slug' => 'logistique',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            25 => 
            array (
                'id' => 26,
                'category_id' => 9,
                'name' => 'Transport',
                'slug' => 'transport',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            26 => 
            array (
                'id' => 27,
                'category_id' => 10,
                'name' => 'Pêche',
                'slug' => 'peche',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            27 => 
            array (
                'id' => 28,
                'category_id' => 10,
                'name' => 'Secteur agricole',
                'slug' => 'secteur-agricole',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            28 => 
            array (
                'id' => 29,
                'category_id' => 10,
                'name' => 'Secteur de l\'élevage',
                'slug' => 'secteur-de-lelevage',
                'description' => NULL,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            29 => 
            array (
                'id' => 30,
                'category_id' => 11,
                'name' => 'Assainissement',
                'slug' => 'assainissement',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            30 => 
            array (
                'id' => 31,
                'category_id' => 11,
                'name' => 'Eau',
                'slug' => 'eau',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            31 => 
            array (
                'id' => 32,
                'category_id' => 11,
                'name' => 'Faune',
                'slug' => 'faune',
                'description' => NULL,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            32 => 
            array (
                'id' => 33,
                'category_id' => 11,
                'name' => 'Énergies renouvelables',
                'slug' => 'energies-renouvelables',
                'description' => NULL,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            33 => 
            array (
                'id' => 34,
                'category_id' => 11,
                'name' => 'Protection environnement',
                'slug' => 'protection-environnement',
                'description' => NULL,
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            34 => 
            array (
                'id' => 35,
                'category_id' => 11,
                'name' => 'Mines',
                'slug' => 'mines',
                'description' => NULL,
                'order' => 6,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            35 => 
            array (
                'id' => 36,
                'category_id' => 12,
                'name' => 'Construction d\'ouvrages',
                'slug' => 'construction-douvrages',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            36 => 
            array (
                'id' => 37,
                'category_id' => 12,
                'name' => 'Information géographique',
                'slug' => 'information-geographique',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            37 => 
            array (
                'id' => 38,
                'category_id' => 12,
                'name' => 'Aménagements urbains',
                'slug' => 'amenagements-urbains',
                'description' => NULL,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            38 => 
            array (
                'id' => 39,
                'category_id' => 12,
                'name' => 'Bâtiments',
                'slug' => 'batiments',
                'description' => NULL,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            39 => 
            array (
                'id' => 40,
                'category_id' => 13,
                'name' => 'Contentieux électoraux',
                'slug' => 'contentieux-electoraux',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            40 => 
            array (
                'id' => 41,
                'category_id' => 13,
                'name' => 'Contrôle de constitutionnalité',
                'slug' => 'controle-de-constitutionnalite',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            41 => 
            array (
                'id' => 42,
                'category_id' => 13,
                'name' => 'Contrôle des partis politiques',
                'slug' => 'controle-des-partis-politiques',
                'description' => NULL,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            42 => 
            array (
                'id' => 43,
                'category_id' => 13,
                'name' => 'Distinction honorifique',
                'slug' => 'distinction-honorifique',
                'description' => NULL,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            43 => 
            array (
                'id' => 44,
                'category_id' => 13,
                'name' => 'Gouvernance administrative/politique/économique',
                'slug' => 'gouvernance-administrativepolitiqueeconomique',
                'description' => NULL,
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            44 => 
            array (
                'id' => 45,
                'category_id' => 14,
                'name' => 'Décentralisation',
                'slug' => 'decentralisation',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            45 => 
            array (
                'id' => 46,
                'category_id' => 14,
                'name' => 'État civil',
                'slug' => 'etat-civil',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            46 => 
            array (
                'id' => 47,
                'category_id' => 14,
                'name' => 'Protection civile',
                'slug' => 'protection-civile',
                'description' => NULL,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            47 => 
            array (
                'id' => 48,
                'category_id' => 14,
                'name' => 'Sécurité',
                'slug' => 'securite',
                'description' => NULL,
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            48 => 
            array (
                'id' => 49,
                'category_id' => 15,
                'name' => 'Loisirs',
                'slug' => 'loisirs',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            49 => 
            array (
                'id' => 50,
                'category_id' => 15,
                'name' => 'Promotion jeunesse',
                'slug' => 'promotion-jeunesse',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            50 => 
            array (
                'id' => 51,
                'category_id' => 15,
                'name' => 'Promotion du sport',
                'slug' => 'promotion-du-sport',
                'description' => NULL,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            51 => 
            array (
                'id' => 52,
                'category_id' => 16,
                'name' => 'Arts et culture',
                'slug' => 'arts-et-culture',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            52 => 
            array (
                'id' => 53,
                'category_id' => 16,
                'name' => 'Tourisme',
                'slug' => 'tourisme',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            53 => 
            array (
                'id' => 54,
                'category_id' => 17,
                'name' => 'Diplomatie',
                'slug' => 'diplomatie',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            54 => 
            array (
                'id' => 55,
                'category_id' => 18,
                'name' => 'Médiation dans le public',
                'slug' => 'mediation-dans-le-public',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            55 => 
            array (
                'id' => 56,
                'category_id' => 19,
                'name' => 'Gestion de carrière',
                'slug' => 'gestion-de-carriere',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            56 => 
            array (
                'id' => 57,
                'category_id' => 19,
                'name' => 'Recrutement',
                'slug' => 'recrutement',
                'description' => NULL,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
            57 => 
            array (
                'id' => 58,
                'category_id' => 20,
                'name' => 'Divers',
                'slug' => 'divers',
                'description' => NULL,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2026-02-20 19:37:34',
                'updated_at' => '2026-02-20 19:37:34',
            ),
        ));
        
        
    }
}